function someoneWasHere (text: string) {
    someone = sprites.create(img`
        ............fffffffff...........
        ...........fffffffffff..........
        ..........fffffffffffff.........
        .........fffffffffffffff........
        ........fffffffffffffffff.......
        ........fffffffffffffffff.......
        ........fffffffffffffffff.......
        ........fffffffffffffffff.......
        ........fffffffffffffffff.......
        ........fffffffffffffffff.......
        ........fffffffffffffffff.......
        ........fffffffffffffffff.......
        ........fffffffffffffffff.......
        .........fffffffffffffff........
        ..........fffffffffffff.........
        ...........fffffffffff..........
        ............fffffffff...........
        ...........fffffffffff..........
        .........fffffffffffffff........
        .......fffffffffffffffffff......
        ......fffffffffffffffffffff.....
        .....fffffffffffffffffffffff....
        ....fffffffffffffffffffffffff...
        ....fffffffffffffffffffffffff...
        ...fffffffffffffffffffffffffff..
        ...fffffffffffffffffffffffffff..
        ..fffffffffffffffffffffffffffff.
        ..fffffffffffffffffffffffffffff.
        ..fffffffffffffffffffffffffffff.
        ..fffffffffffffffffffffffffffff.
        ..fffffffffffffffffffffffffffff.
        ..fffffffffffffffffffffffffffff.
        `, SpriteKind.Player)
    someone.setPosition(101, 110)
    someone.sayText("" + text + " wuz here!")
}
let someone: Sprite = null
scene.setBackgroundColor(3)
someoneWasHere("Mr. Kersting")
